name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "This is a github workflows demo"
      - name: display files
        run: ls -ltr
      - name: add a file
        run: touch file1.txt
      - name: list again
        run: ls -ltr
      - name: print bye
        run: echo "Goodbye from GitHub"
